apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HomeServers/MyTodolist-Infrastructure
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: todolist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
